[package]
name = "http"
version = "0.1.0"
authors = ["Jack Liar"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]
name = "http"

[dependencies]
anyhow = "1.0"
hyperscan = "0.2"
libc = "0.2"
llhttp = { git = "https://github.com/JackLiar/rust-llhttp.git", branch = "phantomdata" }
num-traits = "0.2"
once_cell = "1.6"
serde_json = "1.0"

[dependencies.alphonse-api]
path = "../../api"
optional = false
